#!/bin/env sh


# Ansi color code variables
# RED="\e[0;91m"
# BLUE="\e[0;94m"
# GREEN="\e[0;92m"
# WHITE="\e[0;97m"
# RESET="\e[0m"

WIFI="\uf2ef $(iw wlo1 info | sed -n 's/^.*ssid //p')"
VOL="\uf2ea $(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))"
BATT="\uf129 $(cat /sys/class/power_supply/BAT0/capacity)%"
DATE="\uf14a $(date +'%b %d %l:%M %p')"

echo -e "$WIFI | $VOL | $BATT | $DATE | \uf2dc $USER |"
