#!/bin/env sh


# Ansi color code variables
# RED="\e[0;91m"
# BLUE="\e[0;94m"
# GREEN="\e[0;92m"
# WHITE="\e[0;97m"
# RESET="\e[0m"

WIFI="\uf30f $(iw wlp9s0 info | sed -n 's/^.*ssid //p')"
VOL="\uf309 $(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))"
BATT="\uf12a $(cat /sys/class/power_supply/BAT1/capacity)%"
DATE="\uf14b $(date +'%b %d %l:%M %p')"

echo -e "$WIFI | $VOL | $BATT | $DATE |"
