#!/bin/sh

mod="Mod4"

############
# Appearance
#
riverctl border-width               2
riverctl background-color           0x1c3339
riverctl border-color-focused       0xe3ccc6
riverctl border-color-unfocused     0x1c3339
riverctl xcursor-theme              Adwaita

gsettings set org.gnome.desktop.wm.preferences button-layout " "
gsettings set org.gnome.desktop.interface cursor-theme Adwaita

##########
# Keybinds
#

# Application
riverctl map normal $mod        Return spawn alacritty
riverctl map normal $mod+Shift  Return spawn "alacritty --class terminal"
riverctl map normal $mod        D spawn bemenu-run

# Screenshot
riverctl declare-mode screenshot
riverctl map normal     $mod Print  enter-mode screenshot
riverctl map screenshot $mod Print  enter-mode normal
riverctl map screenshot $mod Return enter-mode normal

riverctl map screenshot $mod        F spawn 'grim' # fullscreen
riverctl map screenshot $mod+Shift  F spawn 'grim - | wl-copy' # F copy to clipboard"
riverctl map screenshot $mod        G spawn 'grim -g "$(slurp)"' # grab screen
riverctl map screenshot $mod+Shift  G spawn 'grim -g "$(slurp)" - | wl-copy' # G copy to clipboard"
# Window management
riverctl map normal $mod+Shift  Q       close
riverctl map normal $mod        Z       zoom
riverctl map normal $mod+Shift  E       exit
riverctl map normal $mod        F       toggle-fullscreen
riverctl map normal $mod        Space   toggle-float
riverctl map normal $mod        Right   focus-view next
riverctl map normal $mod        Left    focus-view previous
riverctl map normal $mod+Shift  Right   swap next
riverctl map normal $mod+Shift  Left    swap previous
riverctl map normal $mod        Period  focus-output next
riverctl map normal $mod        Comma   focus-output previous

# Move views
riverctl map normal $mod+Alt Left   move left 100
riverctl map normal $mod+Alt Down   move down 100
riverctl map normal $mod+Alt Up     move up 100
riverctl map normal $mod+Alt Right  move right 100

# passthrough mode.
riverctl declare-mode passthrough
riverctl map normal         $mod F11 enter-mode passthrough
riverctl map passthrough    $mod F11 enter-mode normal

# resize mode
riverctl declare-mode resize
riverctl map normal $mod R enter-mode resize
riverctl map resize $mod R enter-mode normal

riverctl map resize $mod Left   resize horizontal -100
riverctl map resize $mod Down   resize vertical 100
riverctl map resize $mod Up     resize vertical -100
riverctl map resize $mod Right  resize horizontal 100

######
# Tags
#
for i in $(seq 1 10)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal $mod                $i set-focused-tags $tags
    riverctl map normal $mod+Shift          $i set-view-tags $tags
    riverctl map normal $mod+Control        $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control  $i toggle-view-tags $tags

    if [ "$i" -eq 10 ]; then
        riverctl map normal $mod                0 set-focused-tags $tags
        riverctl map normal $mod+Shift          0 set-views-tags $tags
        riverctl map normal $mod+Control        0 toggle-focused-tags $tags
        riverctl map normal $mod+Shift+Control  0 toggle-view-tags $tags
    fi
done

all_tags=$(((1 << 32) - 1))
riverctl map normal $mod        minus set-focused-tags $all_tags
riverctl map normal $mod+Shift  minus set-view-tags $all_tags

##############
# Special Keys
#
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume    spawn 'amixer set Master 5%+'
    riverctl map $mode None XF86AudioLowerVolume    spawn 'amixer set Master 5%-'
    riverctl map $mode None XF86AudioMute           spawn 'amixer set Master toggle'
    riverctl map $mode None XF86AudioMicMute        spawn 'amixet set Capture toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

#########
# Pointer
#
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

#######
# Input
#
riverctl input "pointer-2-7-SynPS/2_Synaptics_TouchPad" tap enabled
riverctl set-repeat 80 300

########
# Output
#
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

########
# Layout
#
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal $mod+Alt+Control H snap left
riverctl map normal $mod+Alt+Control J snap down
riverctl map normal $mod+Alt+Control K snap up
riverctl map normal $mod+Alt+Control L snap right

riverctl map normal $mod+Shift Up       send-layout-cmd rivertile "main-location top"
riverctl map normal $mod+Shift Right    send-layout-cmd rivertile "main-location right"
riverctl map normal $mod+Shift Down     send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod+Shift Left     send-layout-cmd rivertile "main-location left"


####################
# Application Filter
#
riverctl float-filter-add app-id terminal
riverctl float-filter-add title "Open File"
riverctl csd-filter-add app-id "gedit"


riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
riverctl spawn "river-tag-overlay \
    --tag-amount 10 \
    --anchors 0:1:1:0 \
    --margins 0:10:10:0 \
    --border-colour 0xe3ccc6 \
    --square-size 20 \
    --square-inner-padding 5 \
    --square-padding 5"

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile -view-padding 2 -outer-padding 2
