#!/bin/sh


#############
# Variables
#
mod="Mod4"
wallpaper="$HOME/pics/wpaper/86910-anime-lighthouse-floating_island.jpg -m fill"
default_focused_border_color=0x2fafff
default_unfocused_border_color=0x303030

############
# Appearance
#
riverctl border-width               2
riverctl border-color-focused       $default_focused_border_color
riverctl border-color-unfocused     $default_unfocused_border_color
riverctl xcursor-theme              Adwaita

gsettings set org.gnome.desktop.interface cursor-theme Adwaita

##########
# Keybinds
#

# Application
riverctl map normal $mod        Return  spawn "foot --app-id terminal"
riverctl map normal $mod        P       spawn fuzzel
riverctl map normal $mod        N       spawn nm_dmenu

# Screenshot mode
riverctl declare-mode screenshot
riverctl map normal     $mod Print  enter-mode screenshot
riverctl map screenshot $mod Print  enter-mode normal
riverctl map screenshot None Return enter-mode normal

riverctl map screenshot None    F spawn 'grim'
riverctl map screenshot Shift   F spawn 'grim - | wl-copy'
riverctl map screenshot None    G spawn 'grim -g "$(slurp)"'
riverctl map screenshot Shift   G spawn 'grim -g "$(slurp)" - | wl-copy'

# Window management
riverctl map normal $mod		Q       close
riverctl map normal $mod+Shift  E       spawn 'wlogout -p layer-shell'

riverctl map normal $mod        F       toggle-fullscreen
riverctl map normal $mod        S       toggle-float
riverctl map normal $mod        Space   zoom

riverctl map normal $mod        Right   focus-view next
riverctl map normal $mod        Left    focus-view previous
riverctl map normal $mod+Shift  Right   swap next
riverctl map normal $mod+Shift  Left    swap previous

# Move floating views
riverctl map normal $mod+Alt Left   move left 50
riverctl map normal $mod+Alt Down   move down 50
riverctl map normal $mod+Alt Up     move up 50
riverctl map normal $mod+Alt Right  move right 50

# passthrough mode.
riverctl declare-mode passthrough
riverctl map normal         $mod F11 enter-mode passthrough
riverctl map passthrough    $mod F11 enter-mode normal

# resize mode
riverctl declare-mode resize
riverctl map normal $mod R      enter-mode resize
riverctl map resize $mod R      enter-mode normal
riverctl map resize None Return enter-mode normal

# resize floating window
riverctl map resize None Left   resize horizontal -100
riverctl map resize None Down   resize vertical 100
riverctl map resize None Up     resize vertical -100
riverctl map resize None Right  resize horizontal 100

######
# Tags
#
for i in $(seq 1 10)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal $mod                $i set-focused-tags $tags
    riverctl map normal $mod+Shift          $i set-view-tags $tags
    riverctl map normal $mod+Control        $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control  $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal $mod        minus set-focused-tags $all_tags
riverctl map normal $mod+Shift  minus set-view-tags $all_tags

##############
# Special Keys
#
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume    spawn 'amixer set Master 5%+'
    riverctl map $mode None XF86AudioLowerVolume    spawn 'amixer set Master 5%-'
    riverctl map $mode None XF86AudioMute           spawn 'amixer set Master toggle'
    riverctl map $mode None XF86AudioMicMute        spawn 'amixet set Capture toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

#########
# Pointer
#
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl focus-follows-cursor disabled
riverctl set-cursor-warp on-output-change

#######
# Input
#
riverctl input "pointer-2-7-SynPS/2_Synaptics_TouchPad" tap enabled
riverctl set-repeat 80 300

########
# Output
#
riverctl map normal $mod        Period  focus-output next
riverctl map normal $mod        Comma   focus-output previous
riverctl map normal $mod+Shift  Period  send-to-output next
riverctl map normal $mod+Shift  Comma   send-to-output previous

riverctl map-switch normal lid close spawn "wlr-randr --output eDP-1 --off"
riverctl map-switch normal lid open spawn "wlr-randr --output eDP-1 --on"

########
# Layout
#
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal $mod+Alt+Control H snap left
riverctl map normal $mod+Alt+Control J snap down
riverctl map normal $mod+Alt+Control K snap up
riverctl map normal $mod+Alt+Control L snap right

#riverctl map normal $mod+Shift Up       send-layout-cmd rivertile "main-location top"
#riverctl map normal $mod+Shift Right    send-layout-cmd rivertile "main-location right"
#riverctl map normal $mod+Shift Down     send-layout-cmd rivertile "main-location bottom"
#riverctl map normal $mod+Shift Left     send-layout-cmd rivertile "main-location left"


####################
# Application Filter
#
riverctl rule-add float -app-id Thunar
riverctl rule-add float -app-id thunar
riverctl rule-add float -app-id terminal
riverctl rule-add float -app-id xdg-desktop-portal-gtk
riverctl rule-add float -app-id mousepad
riverctl rule-add float -title "Open File"
riverctl rule-add float -title "Open Folder"
riverctl rule-add float -title "Telegram"
riverctl rule-add float -app-id pavucontrol
riverctl rule-add float -app-id Xfe
riverctl rule-add float -app-id "org.gnome.Nautilus"

riverctl rule-add csd -app-id "gedit"
riverctl rule-add csd -app-id "org.gnome.Nautilus"
###########
# Autostart
#
riverctl spawn 'swaybg -i $wallpaper'
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP"
#riverctl spawn "river-tag-overlay \
#    --timeout 2000 \
#    --tag-amount 9 \
#    --anchors 0:1:1:0 \
#    --margins 0:10:10:0 \
#    --border-colour 0xe3ccc6 \
#    --square-size 20 \
#    --square-inner-padding 5 \
#    --square-padding 5"
riverctl spawn "lxpolkit"
riverctl spawn kanshi

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile -view-padding 4 -outer-padding 4
