#!/bin/env sh

FILENAME="$(date +%Y%m%d%H%M%S%4N).png"
SCREENSHOT_DIR="$(xdg-user-dir PICTURES)/screenshot"
SLURP=0
NOTIFY=0
NOTIFY_SUMMARY="Screenshot saved."
NOTIFY_BODY="Screenshot saved in $SCREENSHOT_DIR"

usage() {
    cat <<EOF
Usage: shot-it [OPTIONS]
Screenshot wrapper for grim and slurp.

Options:
  -c, --dir     Set output directory.
  -d, --delay	Set delay. (default 0)
  -g, --grab    Set region to screenshot. (require: slurp)
  -h, --help    Show help message.
  -n, --notify	Show notify.
EOF
}

while [ "$#" -gt 0 ]; do
    case $1 in
        -h|--help)
            usage
            exit
            ;;
        -c|--dir)
            SCREENSHOT_DIR="$2"
            shift 2
            ;;
        -d|--delay)
            DELAY=$2
            shift 2
            ;;

        -g|--grab)
            SLURP=1
            shift 1
            ;;
        -n|--notify)
            NOTIFY=1
            shift 1
            ;;
        *)
            echo "ERROR: Unknown option \"$PARAM\""
            usage
            exit 1
            ;;
    esac
done

if [ ! -d "$SCREENSHOT_DIR" ]; then
    mkdir -p "$SCREENSHOT_DIR"
fi

COMMAND="grim"

if [ "$SLURP" -eq 1 ]; then
    COMMAND="$COMMAND -g \"$(slurp)\""
fi

COMMAND="$COMMAND $SCREENSHOT_DIR/$FILENAME"

if [[ ${DELAY} -gt 0 ]]; then
    sleep ${DELAY}
fi


eval "$COMMAND" && notify-send "$NOTIFY_SUMMARY" "$NOTIFY_BODY"

# if [ "$NOTIFY" -eq 1 ]; then
# fi
