unbind C-b
set-option -g prefix C-o

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g set-clipboard on

# Status line
set -g status off
set-option -g status-position top

bind C-s set-option -g status

# Pane
set -g pane-border-status top
set -g pane-border-format "#[fg=green](#{window_id}) #{pane_index}/#{pane_current_command}[#S]"

## Pane Resize
## Resize with Ctrl + Arrow keys (5-cell increments)
## The -r flag allows repeated tapping after a single prefix
bind-key -r -T prefix C-Up    resize-pane -U 5
bind-key -r -T prefix C-Down  resize-pane -D 5
bind-key -r -T prefix C-Left  resize-pane -L 5
bind-key -r -T prefix C-Right resize-pane -R 5

# Key Binding
#############

# add binding to reload configuration
bind R source-file ~/.config/tmux/tmux.conf \; display " reloading configuration..."

# Pane spliting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"


set -g status-interval 1
