# -*- conf -*-

login-shell=yes

font=Iosevka:size=12:antialias=true
dpi-aware=no
initial-window-size-chars=80x24

bold-text-in-bright=no

[cursor]
style=block
blink=yes
beam-thickness=1

[mouse]
hide-when-typing=yes

[colors-dark]
background=242424
foreground=f6f3e8

# Normal colors (ansi-color-* faces)
regular0=242424  # black
regular1=b85149  # red
regular2=92a65e  # green
regular3=ccaa8f  # yellow
regular4=5b98c2  # blue
regular5=64619a  # magenta
regular6=3f9f9e  # cyan
regular7=f6f3e8  # white

# Bright colors (ansi-color-bright-* faces)
bright0=444444  # bright black
bright1=e5786d  # bright red
bright2=95e454  # bright green
bright3=edc4a3  # bright yellow
bright4=8ac6f2  # bright blue
bright5=a6a1de  # bright magenta
bright6=70cecc  # bright cyan
bright7=ffffff  # bright white

# Cursor: <text color> <cursor color>
cursor=242424 8ac6f2

# Selection (matches the theme's `region' face)
selection-foreground=f6f3e8
selection-background=444444

# Clickable URLs (matches the theme's `link' face)
urls=8ac6f2
